CREATE TABLE productos(
IDproducto int not null auto_increment,
IDproveedor int not null,
numFactura int default null,
fecEmision date,
numserie varchar(100) not null,
IDFamilia int not null,
IDSubFam int,
IDmarca int,
modelo varchar(100),
tipoUnidad varchar(30),
tipArticulo varchar(30),
descripcion varchar(255),
preUnitario double,
marGanancia double,
precioVenta double,
cantidad double,
pro_peso varchar(20),
pro_tamaño  varchar(20),
pro_alto varchar(20),
pro_largo varchar(20),
pro_ancho varchar(20),
pro_color varchar(30),
pro_incluye varchar(150),
pro_fecRegistro timestamp default current_timestamp,
IDPersonal int not null,
alertAmbar tinyint(1) default false,
alertRojo tinyint(1) default false,
estadoActivo tinyint(1) default true,
PRIMARY_KEY(IDproducto)
);