-- MySQL Script generated by MySQL Workbench
-- mar 20 jun 2017 20:48:42 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema compu
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `compu` ;

-- -----------------------------------------------------
-- Schema compu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compu` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `compu` ;

-- -----------------------------------------------------
-- Table `productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `productos` (
  `IDproductos` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` INT(11) NOT NULL,
  `IDFamilia` INT(11) NOT NULL,
  `IDSubFam` INT(11) NOT NULL,
  `descripcion` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `entradas` INT(11) NOT NULL DEFAULT '0',
  `salidas` INT(11) NOT NULL DEFAULT '0',
  `stock` INT(11) NOT NULL DEFAULT '0',
  `costo` DOUBLE NOT NULL DEFAULT '0',
  `fecRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IDPersonal` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`IDproductos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `familia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `familia` (
  `IDfamilia` INT NOT NULL AUTO_INCREMENT,
  `codigo` CHAR(3) NOT NULL,
  `familia` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `caracteristica1` VARCHAR(45) NULL,
  `caracteristica2` VARCHAR(45) NULL,
  `caracteristica3` VARCHAR(45) NULL,
  `caracteristica4` VARCHAR(45) NULL,
  `caracteristica5` VARCHAR(45) NULL,
  `caracteristica6` VARCHAR(45) NULL,
  `tipoArticulo` VARCHAR(45) NULL,
  `IDprecio` INT NULL,
  PRIMARY KEY (`IDfamilia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Personal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Personal` (
  `IDPersonal` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(60) NOT NULL,
  `paterno` VARCHAR(60) NOT NULL,
  `materno` VARCHAR(60) NOT NULL,
  `dni` CHAR(8) NOT NULL,
  `direccion` VARCHAR(200) NULL,
  `telefono1` VARCHAR(14) NOT NULL,
  `telefono2` VARCHAR(14) NULL,
  `obs` VARCHAR(200) NULL,
  `fecCreacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IDPersonal`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `subfamilias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `subfamilias` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `subfamilias` (
  `idsubfamilias` INT NOT NULL,
  `IDfamilia` INT NOT NULL,
  `codigo` CHAR(3) NOT NULL,
  `subfamilia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsubfamilias`),
  CONSTRAINT `fk_subfamilias_familia`
    FOREIGN KEY (`IDfamilia`)
    REFERENCES `familia` (`IDfamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_subfamilias_familia_idx` ON `subfamilias` (`IDfamilia` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marca` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `codigo` CHAR(3) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `modelo` (
  `idmodelo` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NOT NULL,
  `IDmarca` INT NOT NULL,
  PRIMARY KEY (`idmodelo`),
  CONSTRAINT `fk_modelo_marca`
    FOREIGN KEY (`IDmarca`)
    REFERENCES `marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_modelo_marca_idx` ON `modelo` (`IDmarca` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proveedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `nombreProveedor` VARCHAR(200) NULL,
  `razonSocial` VARCHAR(200) NULL,
  `numRUC` CHAR(11) NULL,
  `direccion` VARCHAR(200) NULL,
  `telfFijo` VARCHAR(10) NULL,
  `celular` VARCHAR(20) NULL,
  `email` VARCHAR(150) NULL,
  `website` VARCHAR(100) NULL,
  `obs` VARCHAR(255) NULL,
  PRIMARY KEY (`idproveedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `precio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `precio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `precio` (
  `idprecio` INT NOT NULL AUTO_INCREMENT,
  `nomPrecio` DOUBLE NOT NULL,
  `descripcion` VARCHAR(60) NULL,
  `IDProducto` INT NOT NULL,
  PRIMARY KEY (`idprecio`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `altaArticulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altaArticulos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `altaArticulos` (
  `idaltaArtic` INT NOT NULL AUTO_INCREMENT,
  `fecAlta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `referencia` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `serie` VARCHAR(100) NOT NULL,
  `IDFamilia` INT NOT NULL,
  `IDsubfamilias` INT NOT NULL,
  `IDmarca` INT NOT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `tipoArticulo` VARCHAR(45) NULL DEFAULT 'Simple',
  `precio` DOUBLE NULL DEFAULT 0.0,
  `margen1` DOUBLE NULL DEFAULT 0.0,
  `margen2` DOUBLE NULL DEFAULT 0.0,
  `margen3` DOUBLE NULL DEFAULT 0.0,
  `margen4` DOUBLE NULL DEFAULT 0.0,
  `dsto1` DOUBLE NULL DEFAULT 0.0,
  `dsto2` DOUBLE NULL DEFAULT 0.0,
  `dsto3` DOUBLE NULL DEFAULT 0.0,
  `dsto4` DOUBLE NULL DEFAULT 0.0,
  `stockIncial` INT NULL DEFAULT 0,
  `garantia` INT NULL DEFAULT 0,
  `peso` VARCHAR(45) NULL DEFAULT NULL,
  `largo` VARCHAR(45) NULL DEFAULT NULL,
  `ancho` VARCHAR(45) NULL DEFAULT NULL,
  `imagen` VARCHAR(45) NULL DEFAULT NULL,
  `obs` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`idaltaArtic`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `login` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `IDpersonal` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `clave` VARCHAR(200) NULL,
  `nivel` INT NULL,
  `estado` INT NULL DEFAULT 1 COMMENT 'Estado:\n1 - activo\n0 - Inactivo\n',
  PRIMARY KEY (`idlogin`),
  CONSTRAINT `fk_login_personal`
    FOREIGN KEY (`IDpersonal`)
    REFERENCES `Personal` (`IDPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_login_personal_idx` ON `login` (`IDpersonal` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `almacen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almacen` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `almacen` (
  `idalmacen` INT NOT NULL AUTO_INCREMENT,
  `almacen` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `IDpersonal` INT NOT NULL,
  PRIMARY KEY (`idalmacen`),
  CONSTRAINT `fk_almacen_personal`
    FOREIGN KEY (`IDpersonal`)
    REFERENCES `Personal` (`IDPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_almacen_personal_idx` ON `almacen` (`IDpersonal` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `altaProductos2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altaProductos2` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `altaProductos2` (
  `idaltaProductos2` INT NOT NULL AUTO_INCREMENT,
  `IDproveedor` INT NOT NULL,
  `numFactura` VARCHAR(50) NULL,
  `fechaEmision` DATE NULL,
  `IDproductos` INT NOT NULL,
  `numeroSerie` VARCHAR(100) NOT NULL,
  `cantidad` INT NULL,
  `unidad` VARCHAR(45) NULL,
  `precioUnitario` DOUBLE NULL,
  `margenganancia` DOUBLE NULL,
  `precioVenta` DOUBLE NULL,
  `fecAlta` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `IDfamilia` INT NOT NULL,
  `IDsubfamilia` INT NULL,
  `IDmarca` INT NULL,
  `modelo` VARCHAR(60) NULL,
  `tipoArticulo` VARCHAR(20) NULL DEFAULT 'Simple',
  `stockInicial` INT NOT NULL,
  `imagen` VARCHAR(250) NULL,
  `obs` VARCHAR(255) NULL,
  `IDPersonal` INT NOT NULL,
  `IDalmacen` INT NOT NULL,
  PRIMARY KEY (`idaltaProductos2`),
  CONSTRAINT `fk_altaProductos2_proveedor`
    FOREIGN KEY (`IDproveedor`)
    REFERENCES `proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_altaProductos2_productos`
    FOREIGN KEY (`IDproductos`)
    REFERENCES `productos` (`IDproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_altaProductos2_familia`
    FOREIGN KEY (`IDfamilia`)
    REFERENCES `familia` (`IDfamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_altaProductos2_subfamilia`
    FOREIGN KEY (`IDsubfamilia`)
    REFERENCES `subfamilias` (`idsubfamilias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_altaProductos2_marca`
    FOREIGN KEY (`IDmarca`)
    REFERENCES `marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_altaProductos2_personal`
    FOREIGN KEY (`IDPersonal`)
    REFERENCES `Personal` (`IDPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_altaProductos2_almacen`
    FOREIGN KEY (`IDalmacen`)
    REFERENCES `almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_altaProductos2_proveedor_idx` ON `altaProductos2` (`IDproveedor` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_altaProductos2_productos_idx` ON `altaProductos2` (`IDproductos` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_altaProductos2_familia_idx` ON `altaProductos2` (`IDfamilia` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_altaProductos2_subfamilia_idx` ON `altaProductos2` (`IDsubfamilia` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_altaProductos2_marca_idx` ON `altaProductos2` (`IDmarca` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_altaProductos2_personal_idx` ON `altaProductos2` (`IDPersonal` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_altaProductos2_almacen_idx` ON `altaProductos2` (`IDalmacen` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
